module.exports = {
  PENDING_PROVIDER: 'PENDING_PROVIDER',
  WAITING_SMS: 'WAITING_SMS',
  SMS_RECEIVED: 'SMS_RECEIVED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED',
  EXPIRED: 'EXPIRED',
  FAILED: 'FAILED'
};
